In [12]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from scipy.stats import mode

In [13]:
iris = datasets.load_iris()

In [14]:
x = pd.DataFrame(iris['data'])

In [15]:
y = iris.target

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [17]:
km = KMeans(n_clusters=4)

In [22]:
cluster = km.fit_predict(x)

In [23]:
lab = np.zeros_like(cluster)

In [24]:
for i in range(4):
    cat = (cluster == i)
    lab[cat] = mode(y[cat])[0]

In [25]:
acc = accuracy_score(y,lab)
acc

0.88

In [26]:
cm = np.array(confusion_matrix(y,lab))
cm

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 18, 32]], dtype=int64)

In [27]:
gmm = GaussianMixture(n_components=4)

In [28]:
cluster = gmm.fit_predict(x)

In [29]:
lab = np.zeros_like(cluster)

In [30]:
for i in range(4):
    cat = (cluster == i)
    lab[cat] = mode(y[cat])[0]

In [31]:
acc = accuracy_score(y,lab)
acc

0.9533333333333334

In [32]:
cm = np.array(confusion_matrix(y,lab))
cm

array([[50,  0,  0],
       [ 0, 43,  7],
       [ 0,  0, 50]], dtype=int64)

In [34]:
ac = AgglomerativeClustering(n_clusters=4)

In [35]:
cluster = ac.fit_predict(x)

In [36]:
lab = np.zeros_like(cluster)

In [37]:
for i in range(4):
    cat = (cluster == i)
    lab[cat] = mode(y[cat])[0]

In [38]:
acc = accuracy_score(y,lab)
acc

0.8933333333333333

In [39]:
cmm = np.array(confusion_matrix(y,lab))
cmm

array([[50,  0,  0],
       [ 0, 49,  1],
       [ 0, 15, 35]], dtype=int64)